name: functions-unit-tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'functions/**'
      - '.github/workflows/functions-unit-tests.yml'
  push:
    branches: [ main ]
    paths:
      - 'functions/**'
      - '.github/workflows/functions-unit-tests.yml'

jobs:
  tests:
    name: Unit Tests (functions)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'functions/requirements.txt'
      - name: Install (pip fallback) + mypy + pytest
        run: |
          python -m pip install --upgrade pip
          # Poetry を使う場合でも、CI では最小依存関係だけで十分なので requirements.txt を利用
          pip install -r requirements.txt pytest mypy
      - name: Run unit tests
        run: pytest -q --maxfail=1
      - name: Type check (mypy)
        run: mypy .
