name: Infra Apply (Deploy)

on:
  workflow_dispatch:
    inputs:
      runIdRef:
        description: 'Reference plan run id (optional for trace)'
        required: false
      confirm:
        description: 'Type APPLY to confirm deployment'
        required: true
        default: 'APPLY'

permissions:
  id-token: write
  contents: read

environment: poc

concurrency:
  group: infra-apply
  cancel-in-progress: false

env:
  LOCATION: japaneast
  RG_ONLY_TEMPLATE: infra/rg-only.bicep
  PARAMETERS_FILE: infra/parameters.poc.json

jobs:
  deploy:
    if: github.event.inputs.confirm == 'APPLY'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create / Update RG only (subscription deployment)
        id: deploy
        run: |
          set -eux
          az deployment sub create \
            --name apply-${{ github.run_id }} \
            --location $LOCATION \
            --template-file $RG_ONLY_TEMPLATE \
            --parameters @$PARAMETERS_FILE \
            --parameters resourceGroupName=$(jq -r '.parameters.resourceGroupName.value' $PARAMETERS_FILE) location=$(jq -r '.parameters.location.value' $PARAMETERS_FILE) | tee deploy-output.json

      - name: Summarize
        run: |
          echo "### Infra Apply Complete" >> $GITHUB_STEP_SUMMARY
          echo "Deployment Name: apply-${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
          echo "Mode: Resource Group only (no Function / Storage / Insights in this phase)" >> $GITHUB_STEP_SUMMARY
          echo "Run Ref (plan): ${{ github.event.inputs.runIdRef }}" >> $GITHUB_STEP_SUMMARY
          echo "Next: Introduce full infra via deploy.subscription.bicep in a later branch." >> $GITHUB_STEP_SUMMARY

