name: Infra Plan (What-if)

on:
  pull_request:
    paths:
      - 'infra/**.bicep'
      - 'infra/**.bicepparam'
      - 'infra/**.json'
      - '.github/workflows/infra-plan.yml'
  push:
    branches: [ main ]
    paths:
      - 'infra/**.bicep'
      - 'infra/**.bicepparam'
      - 'infra/**.json'
      - '.github/workflows/infra-plan.yml'
permissions:
  id-token: write   # required for OIDC federated credentials
  contents: read
concurrency:
  group: infra-plan-${{ github.ref }}
  cancel-in-progress: false

env:
  LOCATION: japaneast
  RG_ONLY_TEMPLATE: infra/rg-only.bicep
  PARAMETERS_FILE: infra/poc.bicepparam

jobs:
  what-if:
    name: What-if (subscription scope)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate required secrets present
        env:
          HAS_CLIENT: ${{ secrets.AZURE_CLIENT_ID }}
          HAS_TENANT: ${{ secrets.AZURE_TENANT_ID }}
          HAS_SUB: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          set -e
          test -n "$HAS_CLIENT" || { echo '::error title=Missing secret::AZURE_CLIENT_ID not configured'; exit 1; }
          test -n "$HAS_TENANT" || { echo '::error title=Missing secret::AZURE_TENANT_ID not configured'; exit 1; }
          test -n "$HAS_SUB" || { echo '::error title=Missing secret::AZURE_SUBSCRIPTION_ID not configured'; exit 1; }
          echo "All required Azure federated credential secrets are present." 

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI Version
        run: az version

      - name: What-if (RG only via bicepparam)
        run: |
          set -eux
          # bicepparam file already binds to rg-only template and inlines parameter values.
          az deployment sub what-if \
            --name plan-${{ github.run_id }} \
            --location $LOCATION \
            --template-file $RG_ONLY_TEMPLATE \
            --parameters @$PARAMETERS_FILE

      - name: Summary
        if: always()
        run: |
          echo "### Infra What-if Result" >> $GITHUB_STEP_SUMMARY
          echo "Template: $RG_ONLY_TEMPLATE" >> $GITHUB_STEP_SUMMARY
          echo "Mode: Resource Group creation only (Function/App resources deferred)" >> $GITHUB_STEP_SUMMARY
          echo "Parameters file: $PARAMETERS_FILE (Bicep params)" >> $GITHUB_STEP_SUMMARY
          echo "To test prod: set PARAMETERS_FILE=infra/prod.bicepparam via workflow_dispatch (future enhancement)" >> $GITHUB_STEP_SUMMARY

